openapi: 3.0.3
info:
  title: Vehicle Analytics API Assessment
  version: 1.0.0
  description: >
    Only the health endpoint is predefined. You must design and implement the
    metadata and data API, then document your full API in this spec (or a separate
    file) and describe how to view it in justification.md.
paths:
  /health:
    get:
      summary: Health check (implemented in skeleton)
      responses:
        '200':
          description: OK
  /metadata:
    get:
      summary: Get metaData
      description: get all sensors metadata, including sensorId, sensorName, and unit
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    sensorId:
                      type: number
                      example: 3000000060002
                    sensorName:
                      type: string
                      example: BRAKE_PRESSURE_FRONT
                    unit:
                      type: string
                      example: kPa
servers:
  - url: http://localhost:4000
    description: Local development server
